# Generated by Django 5.2.2 on 2025-07-30 16:28

import apps.core.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', apps.core.models.base_model.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', apps.core.models.base_model.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', apps.core.models.base_model.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', apps.core.models.base_model.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('named_url', models.CharField(blank=True, max_length=120, verbose_name='Named url')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Url')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.menu', verbose_name='Menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem', verbose_name='Parent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
